// DO NOT EDIT. This code is generated by initgen.
package example

import "github.com/mgnsk/di-container/example/constants"

func initMyInt() constants.MyInt {
	myint := constants.NewMyInt()
	return myint
}
func initMyMultiplier() constants.MyMultiplier {
	mymultiplier := constants.NewMyMultiplier()
	return mymultiplier
}
func initMySentence() MySentence {
	myint := initMyInt()
	mymultiplier := initMyMultiplier()
	mysentence := NewMySentence(myint, mymultiplier)
	return mysentence
}
func initGreeter() Greeter {
	mysentence := initMySentence()
	greeter, err := NewMyGreeter(mysentence)
	if err != nil {
		panic(err)
	}
	return greeter
}
func initMyService() *MyService {
	greeter := initGreeter()
	mymultiplier := initMyMultiplier()
	myservice, err := MyServiceProvider(greeter, mymultiplier)
	if err != nil {
		panic(err)
	}
	return myservice
}
