// package initgen generates a

package main

import (
	"bytes"
	"fmt"
	"go/printer"
	"os"
	"os/exec"
	"path"
	"path/filepath"

	"github.com/mgnsk/di-container/initgen"
	"github.com/moznion/gowrtr/generator"
)

func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	filename, err := filepath.Abs(filepath.Join(".", "initgen.go"))
	check(err)

	fset, node := initgen.ParseFile(filename)

	// Package which is being generated.
	pkg := initgen.GetCurrentPackage()

	// First we generate the generator wrapper which is run later.
	g := generator.NewRoot(
		generator.NewComment(" DO NOT EDIT. This code is generated by `//go:generate initgen` comments"),
		generator.NewPackage("main"),
		generator.NewImport(pkg),
		generator.NewNewline(),
	)

	var genStatements []generator.Statement
	var b bytes.Buffer
	for _, c := range initgen.ParseContainers(node) {
		b.Reset()
		check(printer.Fprint(&b, fset, c.GenFunc))
		genStatements = append(genStatements, generator.NewRawStatement(b.String()))
	}

	g = g.AddStatements(
		generator.NewFunc(
			nil,
			generator.NewFuncSignature("main"),
		).AddStatements(generator.NewRawStatement(path.Base(pkg) + ".Generate()")),
	).
		Gofmt("-s").
		Goimports()

	generated, err := g.Generate(0)
	check(err)

	dir := filepath.Join(filepath.Dir(filename), "tmp")

	os.RemoveAll(dir)

	check(os.Mkdir(dir, os.ModePerm))

	defer os.RemoveAll(dir)

	tmpFile := filepath.Join(dir, "initgen_build.go")

	out, err := os.OpenFile(tmpFile, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0666)
	check(err)

	_, err = fmt.Fprint(out, generated)
	check(err)
	check(out.Close())

	// Run the generator.
	res, err := exec.Command("go", "run", tmpFile).CombinedOutput()
	fmt.Println(string(res))
	check(err)

}
